---
- name: "Install the required packages"
  yum:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ required_packages }}"

- name: Get Nexus user name from systems manager
  set_fact:
    mysql_root_pwd: "{{ lookup('aws_ssm', 'mysql_root_password', decrypt=True, region='eu-west-2' ) }}"

- name: Get Nexus password from systems manager
  set_fact:
    mysql_user_pwd: "{{ lookup('aws_ssm', 'mysql_user_password', decrypt=True, region='eu-west-2' ) }}"

- name: "Start the mysql DB"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: change the db root password
  mysql_user:
    login_user: root
    login_password: ''
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_root_pwd }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: Create the credentials file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart mysql

- name: Create a new database
  mysql_db:
    name: wikidatabase
    state: present

- name: "Download the mediawiki application tarball"
  unarchive:
    src: "{{ application_url }}"
    dest: "{{ destination_dir }}"
    remote_src: yes
    mode: 0644
    owner: root
    group: root

- name: "Create link for the application"
  file:
    src: "{{ destination_dir }}/{{ full_app_name }}"
    dest: "{{ destination_dir }}/{{ app_name }}"
    owner: apache
    group: apache
    state: link

- name: "Start the HTTPD"
  service:
    name: httpd
    state: started
    enabled: yes

- name: "Configure the apache httpd conf file"
  template:
    src: "httpd.conf.j2"
    dest: "{{ httpd_dest_dir }}/conf/httpd.conf"
    owner: root
    force: yes
  notify:
    - restart httpd